services:
  - type: worker
    name: whiteout-survival-bot
    env: python
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --upgrade setuptools wheel
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
    autoDeploy: false
    buildConfig:
      pythonEnvOptions:
        setuptools: true
      pythonVersion: 3.10.13